### ISSUE TITLE
FatZap object in ZFS filesystem

### ISSUE THREAD

**Issue by roopa01** [max123/mdbzfs#8]
Hi,
I am working on ZFS Filesystem to trace data. I got the uberblock details using zdb command:

Uberblock:
	magic = 0000000000bab10c
	version = 5000
	txg = 54
	guid_sum = 14032801381258142085
	timestamp = 1607514721 UTC = Wed Dec  9 17:22:01 2020
	mmp_magic = 00000000a11cea11
	mmp_delay = 0
	mmp_valid = 0
	rootbp = DVA[0]=<0:240002200:200> DVA[1]=<0:260001e00:200> DVA[2]=<0:280005600:200> [L0 DMU objset] fletcher4 lz4 unencrypted LE contiguous unique triple size=1000L/200P birth=54L/54P fill=72 cksum=99dbf6b8d:3e3a721b723:cd24200bab2e:1cb817c85505ed
	checkpoint_txg = 0
I am working on ubuntu 20.04
Zpool has lz4 compression.I moved forward according 
http://www.osdevcon.org/2008/files/osdevcon2008-max.pdf
I reached on step 7 Object directory and got Fatzap object (ZBT_HEADER(0x8000000000000001)) . Now in case of fatzap object it does not have any object id further  to move MOS while in case of microzap object (8000000000000003)
It has structure as follow:
> 0::print -a -t zfs`mzap_phys_t  <-- print an mzap_phys_t
0 uint64_t mz_block_type = 0x8000000000000003...<-- output omitted
40 mzap_ent_phys_t [1] mz_chunk = [

{
40 uint64_t mze_value = 0x2  <-- object id in MOS
48 uint32_t mze_cd = 0
4c uint16_t mze_pad = 0
4e char [50] mze_name = [ "root_dataset" ]
}
Kindly tell me the structure of fatzap object.How can i move to next block from here.

**Comment by max123** [comment]
Looking at illumos/usr/src/uts/common/fs/zfs/sys/zap_impl.h, it looks like it should be 
zfs`zap_phys_t instead of  zfs`mzap_phys_t.  Good luck.  Please let me know if this works (I would be a bit surprised since the paper you mentioned is ~14 years old.
